environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - npm --version
  - npm test

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

# Don't actually build.
build: off
